cleanup

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -151,39 +151,54 @@ jobs:
     steps:
     - uses: actions/checkout@master
     - uses: taiki-e/install-action@cargo-binstall
+
     - name: Set up dependencies
       run: |
         rustup update nightly --no-self-update
         rustup default nightly
+        # Install the version of iai-callgrind-runner that is specified in Cargo.toml
         iai_version="$(cargo metadata --format-version=1 --features icount |
            jq -r '.packages[] | select(.name == "iai-callgrind").version')"
         cargo binstall -y iai-callgrind-runner --version "$iai_version"
         sudo apt-get install valgrind
+
     - uses: Swatinem/rust-cache@v2
     - name: Download musl source
       run: ./ci/download-musl.sh
+
     - name: Run icount benchmarks
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
-        set -xe
+        set -eux
         iai_home="iai-home"
+        # Download the baseline from master
         ./ci/ci-util.py locate-baseline --download --extract
-        cargo bench --no-default-features \
-          --features unstable,unstable-float,icount --bench icount \
-          -- --save-baseline=default --home "$(pwd)/$iai_home" --regression='ir=5.0' \
-          --save-summary
-        echo $?
 
+        # Run iai-callgrind benchmarks
+        cargo bench --no-default-features \
+          --features unstable,unstable-float,icount \
+          --bench icount \
+          -- \
+          --save-baseline=default \
+          --home "$(pwd)/$iai_home" \
+          --regression='ir=5.0' \
+          --save-summary
+        # NB: iai-callgrind should exit on error but does not, so we inspect the sumary
+        # for errors. See  https://github.com/iai-callgrind/iai-callgrind/issues/337
         ./ci/ci-util.py check-regressions "$iai_home"
+
+        # Name and tar the new baseline
         name="baseline-icount-$(date -u +'%Y%m%d%H%M')-${GITHUB_SHA:0:12}"
         echo "BASELINE_NAME=$name" >> "$GITHUB_ENV"
         tar cJf "$name.tar.xz" "$iai_home"
+
     - name: Upload the benchmark baseline
       uses: actions/upload-artifact@v4
       with:
         name: ${{ env.BASELINE_NAME }}
         path: ${{ env.BASELINE_NAME }}.tar.xz
+
     - name: Print test logs if available
       if: always()
       run: if [ -f "target/test-log.txt" ]; then cat target/test-log.txt; fi
